services:
  artesanias-payment-service:
    image: brayan22/artesanias-payment-service:latest
    environment:
      - CONFIG_SERVER_URL=http://artesanias-config-server:9196
      - PORT=9099
      - HOST=https://restauranteapirest.brayandev.info
      - EUREKA_URI=http://artesanias-discovery-server:8761/eureka/
      - HOSTNAME=artesanias-payment-service
      - STRIPE_SECRET_KEY=sk_test_51Qqn3kRtJ4BL2ozwGTyXYtumsWuJg08VCwRvG4DNbuIFICj3FAoeSqLmye4r5e3oZPmSDJD9JDdIBmolfyqH40cT00DsYzBcDA
    hostname: artesanias-payment-service
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  backend:
    external: true