spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:9196}

server:
  port: ${PORT:9099}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${PAYMENT_HOST:localhost}

app:
  stripe:
    secret-key: ${STRIPE_SECRET_KEY:sk_test_51Qqn3kRtJ4BL2ozwGTyXYtumsWuJg08VCwRvG4DNbuIFICj3FAoeSqLmye4r5e3oZPmSDJD9JDdIBmolfyqH40cT00DsYzBcDA}