spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:9196
server:
  port: ${PORT:9099}
  servlet:
    context-path: /payment
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
app:
  stripe:
    secret-key: ${STRIPE_SECRET_KEY:sk_test_51Qqn3kRtJ4BL2ozwGTyXYtumsWuJg08VCwRvG4DNbuIFICj3FAoeSqLmye4r5e3oZPmSDJD9JDdIBmolfyqH40cT00DsYzBcDA}